scenario = balanced
total_processes = 1000
min_arrival = 0
max_arrival = 5000
min_priority = 0
max_priority = 10
high_priority_ratio = 0.5
min_cpu_burst_duration = 5
max_cpu_burst_duration = 50
min_io_burst_duration = 5
max_io_burst_duration = 50
min_cpu_bursts = 2
max_cpu_bursts = 10
quantum = 10
context_switch_cost = 1
rescue_interval = 10
