scenario = cpu_bound
total_processes = 1000
min_arrival = 0
max_arrival = 5000
min_priority = 0
max_priority = 10
high_priority_ratio = 0.5
min_cpu_burst_duration = 50
max_cpu_burst_duration = 200
min_io_burst_duration = 1
max_io_burst_duration = 5
min_cpu_bursts = 1
max_cpu_bursts = 3
quantum = 10
context_switch_cost = 1
