scenario=small
total_processes=5
min_arrival=0
max_arrival=10
min_priority=1
max_priority=5
high_priority_ratio=0.5
min_cpu_burst_duration=1
max_cpu_burst_duration=8
min_io_burst_duration=1
max_io_burst_duration=8
min_cpu_bursts=1
max_cpu_bursts=3
quantum=2
context_switch_cost=1
rescue_interval=10
